name: CD

on:
  push:
    branches:
      - master
      - ipfs-deploy

env:
  node_version: 14

defaults:
  run:
    working-directory: dapp

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: npm install node-gyp
      - run: npm install -g grunt-cli
      - run: npm install
      - run: grunt
      - run: npx ipfs-deploy@8.0.1 ./build -p infura -d cloudflare -O -C
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.PINATA_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.PINATA_SECRET }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: ${{ secrets.CF_ZONE }}
          IPFS_DEPLOY_CLOUDFLARE__RECORD: ${{ secrets.CF_RECORD }}